language: python
python:
  - "2.7"
script: bash _scripts/test.sh
before_deploy:
  - "nvm install 9.5.0"
  - "pip install awscli --upgrade"
  - "git clone https://github.com/awslabs/open-data-registry-browser.git"
  - "mkdir -p open-data-registry-browser/data-sources/awslabs-open-data-registry"
  - "cp -R datasets open-data-registry-browser/data-sources/awslabs-open-data-registry/"
  - "cd open-data-registry-browser"
  - "npm install"
  - "BASE_URL=https://registry.opendata.aws npm run build"
  - "cd ../"
deploy:
  provider: script
  script: bash _scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
